apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-mgmt
  namespace: default
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
